import { useMemo, useState } from "react";
import { ChevronDown, ChevronRight, FolderHeart, MoreHorizontal, Plus } from "lucide-react";
import type { ManualCollection } from "../types";
import { HoverDismissDetails } from "./HoverDismissDetails";

interface Props { items: ManualCollection[]; activeId: string | null; onOpen: (item: ManualCollection) => void; onCreate: (parentId: string | null) => void; onEdit: (item: ManualCollection) => void; onDelete: (item: ManualCollection) => void; onMove: (id: string, parentId: string | null, index: number) => void }

export function ManualCollections({ items, activeId, onOpen, onCreate, onEdit, onDelete, onMove }: Props) {
  const [expanded, setExpanded] = useState<Set<string>>(new Set(items.filter(item => item.parentId === null).map(item => item.id)));
  const children = useMemo(() => { const map = new Map<string | null, ManualCollection[]>(); items.forEach(item => map.set(item.parentId, [...(map.get(item.parentId) || []), item])); map.forEach(values => values.sort((a,b) => a.sortOrder-b.sortOrder)); return map; }, [items]);
  const render = (parentId: string | null, depth: number): React.ReactNode => (children.get(parentId) || []).map((item, index) => { const hasChildren = Boolean(children.get(item.id)?.length); const open = expanded.has(item.id); return <div key={item.id}><div className={`manual-collection-row ${activeId === item.id ? "active" : ""}`} style={{ paddingLeft: 8 + depth * 16 }} data-collection-drop-id={item.id} draggable onDragStart={event => { event.dataTransfer.setData("application/x-stack-collection", item.id); event.dataTransfer.effectAllowed = "move"; }} onDragOver={event => { if (event.dataTransfer.types.includes("application/x-stack-collection")) { event.preventDefault(); const rect=event.currentTarget.getBoundingClientRect(); const ratio=(event.clientY-rect.top)/rect.height; event.currentTarget.dataset.dropZone=ratio<.25?"before":ratio>.75?"after":"inside"; } }} onDragLeave={event=>{delete event.currentTarget.dataset.dropZone;}} onDrop={event => { const source = event.dataTransfer.getData("application/x-stack-collection"); const zone=event.currentTarget.dataset.dropZone; delete event.currentTarget.dataset.dropZone; if (source && source !== item.id) { event.preventDefault(); if(zone==="before"||zone==="after") onMove(source,item.parentId,index+(zone==="after"?1:0)); else { onMove(source, item.id, children.get(item.id)?.length || 0); setExpanded(current => new Set(current).add(item.id)); } } }}><button className="tree-chevron" onClick={() => setExpanded(current => { const next = new Set(current); open ? next.delete(item.id) : next.add(item.id); return next; })}>{hasChildren ? open ? <ChevronDown size={13} /> : <ChevronRight size={13} /> : <span />}</button><button className="manual-collection-main" onClick={() => onOpen(item)}><FolderHeart size={15} /><span>{item.name}</span><small>{item.directAssetCount}{item.descendantAssetCount !== item.directAssetCount ? ` / ${item.descendantAssetCount}` : ""}</small></button><HoverDismissDetails className="tree-menu"><summary><MoreHorizontal size={14} /></summary><div><button onClick={() => onCreate(item.id)}>新建子合集</button><button onClick={() => onEdit(item)}>编辑</button><button className="danger" onClick={() => onDelete(item)}>删除</button></div></HoverDismissDetails></div>{open && render(item.id, depth + 1)}</div>; });
  return <section className="manual-collections"><div className="sidebar-label"><span>合集</span><button title="新建合集" onClick={() => onCreate(null)}><Plus size={13} /></button></div><div className="manual-collection-tree" data-collection-root onDragOver={event => { if (event.dataTransfer.types.includes("application/x-stack-collection")) event.preventDefault(); }} onDrop={event => { const source = event.dataTransfer.getData("application/x-stack-collection"); if (source && event.target === event.currentTarget) onMove(source, null, children.get(null)?.length || 0); }}>{items.length ? render(null, 0) : <button className="empty-collection-create" onClick={() => onCreate(null)}>创建第一个合集</button>}</div></section>;
}
