import { open } from "@tauri-apps/plugin-dialog";
import { Archive, ArrowLeft, BriefcaseBusiness, CalendarDays, Check, ChevronRight, Clapperboard, ExternalLink, FilePlus2, FolderOpen, Images, LayoutDashboard, Link2, ListTodo, MoreHorizontal, Plus, RotateCcw, Settings2, Trash2, Unlink, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { api, mediaLibraryFileUrl } from "../lib/api";
import type { AssetDetail, ContentLanguage, CreativeProject, MediaEntry, MediaEntryDetail, ProjectAssetLink, ProjectAssetStatus, ProjectInput, ProjectPathInput, ProjectSummary, ProjectTask, ProjectTaskInput, ProjectTaskPriority, ProjectTaskStatus, ProjectType, ProjectUnit, ProjectUnitInput, ReferenceBoardSummary } from "../types";
import { ImagePreview } from "./ImagePreview";
import { DetailPanel } from "./DetailPanel";
import { MediaDetail } from "./MediaLibraryView";
import { ContextMenu, type ContextMenuItem } from "./ContextMenu";

const typeLabels: Record<ProjectType, string> = { still: "静帧作品", scene: "场景项目", animation: "动画 / 短片" };
const statusLabels = { planning: "策划中", active: "制作中", paused: "暂停", completed: "已完成", archived: "已归档" } as const;
const assetStatusLabels: Record<ProjectAssetStatus, string> = { candidate: "候选", selected: "已选用", used: "已使用", rejected: "不采用" };
const taskColumns: Array<{ id: ProjectTaskStatus; label: string }> = [{ id: "todo", label: "待办" }, { id: "in_progress", label: "进行中" }, { id: "review", label: "待检查" }, { id: "done", label: "完成" }];
const emptyProject = (): ProjectInput => ({ name: "", description: "", projectType: "scene", status: "planning", targetTools: [], versions: [], resolutionWidth: 1920, resolutionHeight: 1080, frameRate: 24, coverAssetId: null, coverMediaEntryId: null });

interface Props { contentLanguage: ContentLanguage; notify: (message: string, error?: boolean) => void; onOpenReference: (boardId: string) => void; onEditAsset: (id: string) => void; refreshKey?: number }

export function ProjectHub({ contentLanguage, notify, onOpenReference, onEditAsset, refreshKey = 0 }: Props) {
  const [projects, setProjects] = useState<ProjectSummary[]>([]);
  const [active, setActive] = useState<CreativeProject | null>(null);
  const [showArchived, setShowArchived] = useState(false);
  const [editing, setEditing] = useState<ProjectInput | null>(null);
  const [tab, setTab] = useState<"overview" | "assets" | "units" | "tasks" | "boards" | "paths">("overview");
  const [loading, setLoading] = useState(true);
  const [inspectedAsset, setInspectedAsset] = useState<AssetDetail | null>(null);
  const [inspectedMedia, setInspectedMedia] = useState<MediaEntryDetail | null>(null);
  const [checkingLink, setCheckingLink] = useState(false);
  const [contextMenu, setContextMenu] = useState<{x:number;y:number;title:string;items:ContextMenuItem[]}|null>(null);
  const refreshList = useCallback(async () => { setLoading(true); try { setProjects(await api.listProjects(showArchived)); } catch (error) { notify(String(error), true); } finally { setLoading(false); } }, [showArchived, notify]);
  const refreshActive = useCallback(async (markOpened = false) => { if (!active) return; try { const value = await api.getProject(active.id, contentLanguage, markOpened); setActive(value); setProjects(previous => previous.map(item => item.id === value.id ? value : item)); } catch (error) { notify(String(error), true); } }, [active?.id, contentLanguage, notify]);
  useEffect(() => { void refreshList(); }, [refreshList, refreshKey]);
  useEffect(() => { if (active) void refreshActive(false); }, [contentLanguage]);
  const openProject = async (id: string) => { try { setActive(await api.getProject(id, contentLanguage, true)); setTab("overview"); } catch (error) { notify(String(error), true); } };
  const saveProject = async (input: ProjectInput, coverPath?: string) => { try { let next=input;if(coverPath){const result=await api.importMediaEntries({kind:"image",paths:[coverPath],folderId:null,tags:[],favorite:false});const row=result.rows[0];const entryId=row?.entryId||row?.duplicateEntryId;if(!entryId)throw new Error(row?.message||"项目封面导入失败");next={...input,coverAssetId:null,coverMediaEntryId:entryId}}const saved = await api.saveProject(next); setEditing(null); setActive(saved); await refreshList(); notify(input.id ? "项目已更新" : "项目已创建"); } catch (error) { notify(`保存项目失败：${String(error)}`, true); } };
  const openAsset=async(id:string)=>{try{setInspectedAsset(await api.getAsset(id,contentLanguage))}catch(error){notify(String(error),true)}};
  const openMedia=async(id:string)=>{try{setInspectedMedia(await api.getMediaEntry(id))}catch(error){notify(String(error),true)}};
  const archive = async (project: ProjectSummary, value: boolean) => { try { await api.archiveProject(project.id, value); if (active?.id === project.id) setActive(null); await refreshList(); notify(value ? "项目已归档" : "项目已恢复到策划中"); } catch (error) { notify(String(error), true); } };
  const purge = async (project: ProjectSummary) => { if (!window.confirm(`永久删除项目“${project.name}”？\n素材和参考板不会删除，但项目任务与关联将无法恢复。`)) return; try { await api.deleteProject(project.id); await refreshList(); notify("项目已永久删除"); } catch (error) { notify(String(error), true); } };
  if (active) return <>
    <ProjectWorkspace project={active} tab={tab} setTab={setTab} contentLanguage={contentLanguage} notify={notify} onBack={() => { setActive(null); void refreshList(); }} onEdit={() => setEditing(toInput(active))} onRefresh={() => refreshActive(false)} onOpenReference={onOpenReference} onOpenAsset={openAsset} onOpenMedia={openMedia} />
    {editing && <ProjectEditor value={editing} onClose={() => setEditing(null)} onSave={saveProject} />}
    {inspectedAsset && <ProjectAssetInspector asset={inspectedAsset} contentLanguage={contentLanguage} checkingLink={checkingLink} onClose={() => setInspectedAsset(null)} onEdit={() => { const id=inspectedAsset.id;setInspectedAsset(null);onEditAsset(id); }} onRefresh={async()=>setInspectedAsset(await api.getAsset(inspectedAsset.id,contentLanguage))} onCheckLink={async()=>{setCheckingLink(true);try{await api.checkAssetShareLink(inspectedAsset.id);setInspectedAsset(await api.getAsset(inspectedAsset.id,contentLanguage))}finally{setCheckingLink(false)}}} onDeleted={async()=>{setInspectedAsset(null);await refreshActive()}} notify={notify} />}
    {inspectedMedia && <><button className="inspector-backdrop" aria-label="关闭媒体详情" onClick={()=>setInspectedMedia(null)} /><MediaDetail detail={inspectedMedia} onClose={()=>setInspectedMedia(null)} onChanged={async()=>{setInspectedMedia(await api.getMediaEntry(inspectedMedia.id));await refreshActive()}} onNotify={notify}/></>}
  </>;
  return <section className="project-hub">
    <header className="module-page-header"><div><span className="eyebrow">CREATIVE WORKSPACE</span><h1>创作项目</h1><p>把素材、参考、镜头和制作任务组织成可执行的作品计划。</p></div><div><label className="toggle-line"><input type="checkbox" checked={showArchived} onChange={event => setShowArchived(event.target.checked)} />显示已归档</label><button className="primary-button" onClick={() => setEditing(emptyProject())}><Plus size={16} />新建项目</button></div></header>
    {loading ? <div className="loading-state">正在读取项目…</div> : projects.length ? <div className="project-card-grid">{projects.map(project => <article className="project-card" key={project.id} onContextMenu={event=>{event.preventDefault();setContextMenu({x:event.clientX,y:event.clientY,title:project.name,items:[{label:"打开项目",run:()=>void openProject(project.id)},{label:"编辑项目",run:()=>setEditing(toInput(project))},{label:project.status==="archived"?"恢复项目":"归档项目",run:()=>void archive(project,project.status!=="archived")},{label:"永久删除项目",danger:true,disabled:project.status!=="archived",run:()=>void purge(project)}]})}}>
      <button className="project-cover" onClick={() => void openProject(project.id)}><ProjectCover project={project} /><span>{typeLabels[project.projectType]}</span></button>
      <div className="project-card-body"><div className="project-title-row"><div><span className={`project-status ${project.status}`}>{statusLabels[project.status]}</span><h3>{project.name}</h3></div><ProjectMenu project={project} onEdit={() => setEditing(toInput(project))} onArchive={() => void archive(project, project.status !== "archived")} onDelete={() => void purge(project)} /></div>
      <p>{project.description || "暂无项目说明"}</p><div className="project-stats"><span><Images size={14} />{project.assetCount} 素材</span><span><ListTodo size={14} />{project.completedTaskCount}/{project.taskCount} 任务</span>{project.reviewTaskCount > 0 && <span className="review"><Check size={14} />{project.reviewTaskCount} 待检查</span>}</div>
      <div className="project-progress"><i style={{ width: `${project.progress}%` }} /><span>{project.progress}%</span></div><button className="project-open" onClick={() => void openProject(project.id)}>打开工作区 <ChevronRight size={16} /></button></div>
    </article>)}</div> : <div className="empty-state"><BriefcaseBusiness size={44} /><h2>从一个作品开始</h2><p>建立项目后，可以集中整理候选素材、镜头、任务、参考板和本地工程入口。</p><button className="primary-button" onClick={() => setEditing(emptyProject())}><Plus size={16} />创建第一个项目</button></div>}
    {editing && <ProjectEditor value={editing} onClose={() => setEditing(null)} onSave={saveProject} />}
    {contextMenu&&<ContextMenu {...contextMenu} onClose={()=>setContextMenu(null)}/>}
  </section>;
}

function ProjectWorkspace({ project, tab, setTab, contentLanguage, notify, onBack, onEdit, onRefresh, onOpenReference, onOpenAsset, onOpenMedia }: { project: CreativeProject; tab: string; setTab: (value: any) => void; contentLanguage: ContentLanguage; notify: Props["notify"]; onBack: () => void; onEdit: () => void; onRefresh: () => Promise<void>; onOpenReference: (id: string) => void; onOpenAsset:(id:string)=>void; onOpenMedia:(id:string)=>void }) {
  const tabs = [{ id: "overview", label: "总览", icon: LayoutDashboard }, { id: "assets", label: `项目素材 ${project.assetCount}`, icon: Images }, { id: "media", label: `关联媒体 ${project.media.length}`, icon: Images }, { id: "units", label: "场景 / 镜头", icon: Clapperboard }, { id: "tasks", label: `任务 ${project.taskCount}`, icon: ListTodo }, { id: "boards", label: "参考板", icon: Link2 }, { id: "paths", label: "工程入口", icon: FolderOpen }];
  return <section className="project-workspace"><header className="project-workspace-header"><button className="icon-button" onClick={onBack}><ArrowLeft size={19} /></button><div className="project-workspace-cover"><ProjectCover project={project} /></div><div><span className={`project-status ${project.status}`}>{statusLabels[project.status]}</span><h1>{project.name}</h1><p>{typeLabels[project.projectType]} · {[...project.targetTools, ...project.versions].join(" · ") || "未指定软件"}</p></div><button className="secondary-button" onClick={onEdit}><Settings2 size={16} />项目设置</button></header>
    <nav className="project-tabs">{tabs.map(item => { const Icon = item.icon; return <button key={item.id} className={tab === item.id ? "active" : ""} onClick={() => setTab(item.id)}><Icon size={16} />{item.label}</button>; })}</nav>
    <div className="project-tab-content">{tab === "overview" ? <ProjectOverview project={project} setTab={setTab} /> : tab === "assets" ? <ProjectAssets project={project} notify={notify} refresh={onRefresh} onOpenAsset={onOpenAsset} /> : tab === "media" ? <ProjectMedia project={project} onOpenMedia={onOpenMedia} /> : tab === "units" ? <ProjectUnits project={project} notify={notify} refresh={onRefresh} onOpenMedia={onOpenMedia} /> : tab === "tasks" ? <ProjectTasks project={project} notify={notify} refresh={onRefresh} /> : tab === "boards" ? <ProjectBoards project={project} notify={notify} refresh={onRefresh} onOpenReference={onOpenReference} /> : <ProjectPaths project={project} notify={notify} refresh={onRefresh} />}</div>
  </section>;
}

function ProjectCover({project}:{project:ProjectSummary}) {
  return project.coverMediaFileId ? <img src={mediaLibraryFileUrl(project.coverMediaFileId)} alt={project.name} loading="lazy"/> : <ImagePreview imageId={project.coverImageId} alt={project.name}/>;
}

function ProjectMedia({project,onOpenMedia}:{project:CreativeProject;onOpenMedia:(id:string)=>void}) {
  const labels={image:"图片",model:"三维模型",audio:"音频",video:"视频"} as const;
  return <div className="project-media-groups">{(["image","model","audio","video"] as const).map(kind=>{
    const entries=project.media.filter(entry=>entry.kind===kind);
    if(!entries.length)return null;
    return <section className="project-panel" key={kind}><header><h3>{labels[kind]} · {entries.length}</h3></header><div className="project-media-grid">{entries.map(entry=><button key={entry.id} className="project-media-card" onClick={()=>onOpenMedia(entry.id)}>
      {entry.thumbnailFileId?<img src={mediaLibraryFileUrl(entry.thumbnailFileId)} alt="" loading="lazy"/>:<span className="project-media-placeholder">{kind==="model"?"3D":kind.toUpperCase()}</span>}
      <strong>{entry.name}</strong><small>{entry.format.toUpperCase()}</small>
    </button>)}</div></section>;
  })}{!project.media.length&&<div className="empty-state compact"><Images size={34}/><strong>还没有关联媒体</strong><span>在图片、模型、音频或视频库的详情中选择“加入项目”。</span></div>}</div>;
}

function ProjectVideoPicker({onClose,onChoose}:{onClose:()=>void;onChoose:(entryId:string)=>void}) {
  const [query,setQuery]=useState("");
  const [entries,setEntries]=useState<MediaEntry[]>([]);
  const [loading,setLoading]=useState(true);
  useEffect(()=>{let cancelled=false;const timer=window.setTimeout(()=>{setLoading(true);void api.searchMediaEntries({kind:"video",query,folderId:null,includeChildFolders:true,tags:[],formats:[],favoriteOnly:false,sort:"updated",offset:0,limit:100}).then(page=>{if(!cancelled)setEntries(page.items)}).catch(()=>{if(!cancelled)setEntries([])}).finally(()=>{if(!cancelled)setLoading(false)})},180);return()=>{cancelled=true;window.clearTimeout(timer)}},[query]);
  return <div className="modal-backdrop"><section className="modal-card project-video-picker" role="dialog" aria-modal="true"><header><h2>从视频库选择</h2><button className="icon-button" onClick={onClose}><X size={18}/></button></header><input autoFocus value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索视频名称或标签…"/><div className="project-video-picker-list">{loading?<p>正在搜索…</p>:entries.length?entries.map(entry=><button key={entry.id} onClick={()=>onChoose(entry.id)}><strong>{entry.name}</strong><small>{entry.format.toUpperCase()}</small></button>):<p>没有找到视频。你也可以直接上传。</p>}</div></section></div>;
}

function ProjectAssetInspector({asset,contentLanguage,checkingLink,onClose,onEdit,onRefresh,onCheckLink,onDeleted,notify}:{asset:AssetDetail;contentLanguage:ContentLanguage;checkingLink:boolean;onClose:()=>void;onEdit:()=>void;onRefresh:()=>Promise<void>;onCheckLink:()=>Promise<void>;onDeleted:()=>Promise<void>;notify:Props["notify"]}) {
  const run=(promise:Promise<unknown>)=>{void promise.catch(error=>notify(String(error),true))};
  return <><button className="inspector-backdrop" aria-label="关闭素材详情" onClick={onClose}/><DetailPanel asset={asset} contentLanguage={contentLanguage} loading={false} onClose={onClose} onEdit={onEdit} onDelete={()=>{if(!window.confirm(`将“${asset.name}”移入回收站？`))return;run(api.deleteLibraryItems({assetIds:[asset.id],categoryId:null}).then(onDeleted))}} onFavorite={()=>run(api.setFavorite(asset.id,!asset.favorite).then(onRefresh))} onOpen={()=>run(api.openShare(asset.id))} onSourceOpen={()=>{if(asset.sourceUrl)run(api.openExternal(asset.sourceUrl))}} onOpenExternal={url=>run(api.openExternal(url))} onCopy={()=>run(api.copyCode(asset.id).then(()=>notify("提取码已复制")))} onCheckLink={()=>run(onCheckLink())} checkingLink={checkingLink}/></>;
}

function ProjectOverview({ project, setTab }: { project: CreativeProject; setTab: (value: any) => void }) {
  const next = project.tasks.filter(task => task.status !== "done").slice(0, 5);
  return <div className="project-overview"><div className="project-metric-grid"><Metric label="任务进度" value={`${project.progress}%`} detail={`${project.completedTaskCount} / ${project.taskCount} 已完成`} /><Metric label="项目素材" value={String(project.assetCount)} detail={project.unavailableAssetCount ? `${project.unavailableAssetCount} 项暂不可用` : "全部可用"} /><Metric label="待检查" value={String(project.reviewTaskCount)} detail="等待最后确认" /><Metric label="场景 / 镜头" value={String(project.units.length)} detail="制作单元" /></div>
    <div className="project-overview-grid"><section className="project-panel"><header><h3>下一步任务</h3><button onClick={() => setTab("tasks")}>打开看板</button></header>{next.length ? next.map(task => <div className="next-task" key={task.id}><span className={`priority ${task.priority}`} /> <strong>{task.title}</strong><small>{task.dueDate || "无截止日期"}</small></div>) : <div className="empty-inline">暂无待办任务</div>}</section>
    <section className="project-panel"><header><h3>主参考板</h3><button onClick={() => setTab("boards")}>管理关联</button></header>{project.boards.find(board => board.isMain) ? <div className="board-summary"><Images size={32} /><strong>{project.boards.find(board => board.isMain)?.name}</strong><span>{project.boards.find(board => board.isMain)?.itemCount} 张参考图</span></div> : <div className="empty-inline">还没有设置主参考板</div>}</section></div></div>;
}

function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <article className="project-metric"><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>; }

function ProjectAssets({ project, notify, refresh, onOpenAsset }: { project: CreativeProject; notify: Props["notify"]; refresh: () => Promise<void>; onOpenAsset:(id:string)=>void }) {
  const [selected, setSelected] = useState<Set<string>>(new Set()); const [status, setStatus] = useState<ProjectAssetStatus | "all">("all"); const [query, setQuery] = useState("");
  const [contextMenu,setContextMenu]=useState<{x:number;y:number;title:string;items:ContextMenuItem[]}|null>(null);
  const normalizedQuery = query.trim().toLocaleLowerCase();
  const assets = project.assets.filter(asset => (status === "all" || asset.status === status) && (!normalizedQuery || [asset.name, asset.categoryName, asset.purpose, asset.note].some(value => value?.toLocaleLowerCase().includes(normalizedQuery))));
  const update = async (value: ProjectAssetStatus) => { if (!selected.size) return; try { await api.updateProjectAssets({ projectId: project.id, assetIds: [...selected], status: value }); setSelected(new Set()); await refresh(); notify("项目素材状态已更新"); } catch (error) { notify(String(error), true); } };
  const remove = async () => { if (!selected.size || !window.confirm(`从项目移出 ${selected.size} 项素材？素材库原始内容不会删除。`)) return; try { await api.removeProjectAssets(project.id, [...selected]); setSelected(new Set()); await refresh(); } catch (error) { notify(String(error), true); } };
  const editNotes = async () => { if (!selected.size) return; const purpose = window.prompt("这些素材在项目中的用途（留空将清空）", selected.size === 1 ? project.assets.find(item => selected.has(item.assetId))?.purpose || "" : ""); if (purpose === null) return; const note = window.prompt("项目备注（留空将清空）", selected.size === 1 ? project.assets.find(item => selected.has(item.assetId))?.note || "" : ""); if (note === null) return; try { await api.updateProjectAssets({ projectId: project.id, assetIds: [...selected], purpose, note }); await refresh(); notify("用途与备注已更新"); } catch (error) { notify(String(error), true); } };
  const linkUnit = async (unitId: string) => { if (!selected.size || !unitId) return; try { await api.updateProjectAssets({ projectId: project.id, assetIds: [...selected], unitIds: unitId === "clear" ? [] : [unitId] }); await refresh(); notify(unitId === "clear" ? "已清除制作单元关联" : "已关联场景 / 镜头"); } catch (error) { notify(String(error), true); } };
  const setCover = async () => { const id = [...selected][0]; if (selected.size !== 1 || !id) return; try { await api.saveProject({ ...toInput(project), coverAssetId: id, coverMediaEntryId: null }); await refresh(); notify("项目封面已更新"); } catch (error) { notify(String(error), true); } };
  const toBoard = async () => { if (!project.mainBoardId || !selected.size) { notify(project.mainBoardId ? "请先选择素材" : "请先设置主参考板", true); return; } try { const imageIds = await api.prepareReferenceCoverIds([...selected]); const result = await api.addAssetImagesToBoard(project.mainBoardId, imageIds, { x: 0, y: 0 }); notify(`已加入主参考板 ${result.items.length} 张图片${result.skipped ? `，跳过 ${result.skipped} 张` : ""}`); } catch (error) { notify(String(error), true); } };
  return <div className="project-assets"><div className="project-tools"><input className="project-asset-search" value={query} onChange={event => setQuery(event.target.value)} placeholder="搜索项目素材、分类、用途或备注…" /><select value={status} onChange={event => setStatus(event.target.value as any)}><option value="all">全部使用状态</option>{Object.entries(assetStatusLabels).map(([id, label]) => <option value={id} key={id}>{label}</option>)}</select><span>{selected.size} 项已选择</span><select defaultValue="" onChange={event => { if (event.target.value) void update(event.target.value as ProjectAssetStatus); event.currentTarget.value = ""; }}><option value="">批量更改状态…</option>{Object.entries(assetStatusLabels).map(([id, label]) => <option value={id} key={id}>{label}</option>)}</select><button className="secondary-button compact" onClick={() => void toBoard()}><Images size={14} />加入主参考板</button><button className="secondary-button compact danger" onClick={() => void remove()}><Unlink size={14} />移出项目</button></div>
    <div className="project-tools project-asset-secondary"><select defaultValue="" onChange={event => { void linkUnit(event.target.value); event.currentTarget.value = ""; }}><option value="">关联场景 / 镜头…</option><option value="clear">清除关联</option>{project.units.map(unit => <option value={unit.id} key={unit.id}>{unit.kind === "shot" ? "镜头" : "场景"} · {unit.name}</option>)}</select><button className="secondary-button compact" disabled={!selected.size} onClick={() => void editNotes()}>用途与备注</button><button className="secondary-button compact" disabled={selected.size !== 1 || project.assets.find(item => selected.has(item.assetId))?.unavailable} onClick={() => void setCover()}>设为项目封面</button></div>
    {assets.length ? <div className="project-asset-grid">{assets.map(asset => <article key={asset.assetId} className={`${asset.unavailable ? "unavailable" : ""} ${selected.has(asset.assetId) ? "selected" : ""}`} onClick={() => !asset.unavailable&&onOpenAsset(asset.assetId)} onContextMenu={event=>{event.preventDefault();const ids=selected.has(asset.assetId)?[...selected]:[asset.assetId];setContextMenu({x:event.clientX,y:event.clientY,title:ids.length===1?asset.name:`${ids.length} 项项目素材`,items:[{label:"查看素材详情",disabled:ids.length!==1||asset.unavailable,run:()=>onOpenAsset(asset.assetId)},{label:"选择这些素材",run:()=>setSelected(new Set(ids))},{label:"设为项目封面",disabled:ids.length!==1||asset.unavailable,run:()=>{void api.saveProject({...toInput(project),coverAssetId:asset.assetId,coverMediaEntryId:null}).then(refresh).catch(error=>notify(String(error),true))}},{label:"从项目移出",danger:true,run:()=>{if(!window.confirm(`从项目移出 ${ids.length} 项素材？`))return;void api.removeProjectAssets(project.id,ids).then(refresh).catch(error=>notify(String(error),true))}}]})}}><button className={`project-asset-select ${selected.has(asset.assetId)?"active":""}`} aria-label={selected.has(asset.assetId)?"取消选择":"选择项目素材"} onClick={event=>{event.stopPropagation();setSelected(previous=>{const next=new Set(previous);next.has(asset.assetId)?next.delete(asset.assetId):next.add(asset.assetId);return next})}}>{selected.has(asset.assetId)&&<Check size={13}/>}</button><ImagePreview imageId={asset.coverImageId} alt={asset.name} /><div><span className={`asset-use ${asset.status}`}>{assetStatusLabels[asset.status]}</span><strong>{asset.name}</strong><small>{asset.unavailable ? "素材在回收站中，暂不可用" : asset.categoryName || "未分类"}</small>{asset.purpose && <p>{asset.purpose}</p>}{asset.note && <p className="note">{asset.note}</p>}</div></article>)}</div> : <div className="empty-state compact"><Images size={34} /><strong>当前条件下没有项目素材</strong><span>可以从素材详情或素材库多选工具栏加入。</span></div>}
    {contextMenu&&<ContextMenu {...contextMenu} onClose={()=>setContextMenu(null)}/>}
  </div>;
}

function ProjectUnits({ project, notify, refresh, onOpenMedia }: { project: CreativeProject; notify: Props["notify"]; refresh: () => Promise<void>; onOpenMedia:(id:string)=>void }) {
  const [editing, setEditing] = useState<ProjectUnitInput | null>(null); const scenes = project.units.filter(unit => unit.kind === "scene");
  const [videoPickerShot,setVideoPickerShot]=useState<string|null>(null);
  const setVideo=async(shotId:string,entryId:string|null)=>{try{await api.setProjectShotVideo(shotId,entryId);await refresh();notify(entryId?"镜头视频已关联":"镜头视频关联已移除")}catch(error){notify(String(error),true)}};
  const uploadVideo=async(shotId:string)=>{const path=await open({multiple:false,directory:false,filters:[{name:"视频",extensions:["mp4","webm","mov","mkv"]}]});if(typeof path!=="string")return;try{const report=await api.importMediaEntries({kind:"video",paths:[path],folderId:null,tags:[],favorite:false});const row=report.rows[0];const id=row?.entryId||row?.duplicateEntryId;if(!id)throw new Error(row?.message||"视频导入失败");await setVideo(shotId,id)}catch(error){notify(`镜头视频上传失败：${String(error)}`,true)}};
  const create = (kind: "scene" | "shot", parentId: string | null) => setEditing({ projectId: project.id, parentId, kind, name: "", description: "", startFrame: kind === "shot" ? 1 : null, endFrame: kind === "shot" ? 100 : null, resolutionWidth: null, resolutionHeight: null, frameRate: null });
  const save = async (input: ProjectUnitInput) => { try { await api.saveProjectUnit(input); setEditing(null); await refresh(); } catch (error) { notify(String(error), true); } };
  const remove = async (unit: ProjectUnit) => { const shots = unit.kind === "scene" ? project.units.filter(item => item.parentId === unit.id).length : 0; const tasks = project.tasks.filter(task => task.unitId === unit.id || (unit.kind === "scene" && project.units.some(item => item.parentId === unit.id && item.id === task.unitId))).length; if (!window.confirm(`删除“${unit.name}”？${shots ? `\n将同时删除 ${shots} 个镜头` : ""}${tasks ? `和 ${tasks} 个关联任务` : ""}。项目素材不会移除。`)) return; try { await api.deleteProjectUnit(unit.id); await refresh(); } catch (error) { notify(String(error), true); } };
  return <div><div className="project-tools"><button className="primary-button compact" onClick={() => create("scene", null)}><Plus size={14} />新建场景</button></div>
    {scenes.length ? <div className="scene-list">{scenes.map(scene => <section className="scene-card" key={scene.id}>
      <header><div><Clapperboard size={18} /><strong>{scene.name}</strong><span>{scene.description}</span></div><button onClick={() => create("shot", scene.id)}><Plus size={14} />镜头</button><button onClick={() => setEditing(toUnitInput(scene))}>编辑</button><button className="danger" onClick={() => void remove(scene)}>删除</button></header>
      <div className="shot-list">{project.units.filter(unit => unit.parentId === scene.id).map(shot => <article key={shot.id} className="shot-card">
        <div className="shot-heading"><strong>{shot.name}</strong><span>{shot.startFrame ?? "?"}–{shot.endFrame ?? "?"} 帧{shot.frameRate ? ` · ${shot.frameRate} fps` : ""}</span></div>
        {shot.videoStreamFileId && <div className="shot-video"><video src={mediaLibraryFileUrl(shot.videoStreamFileId)} controls preload="metadata"/><button onClick={()=>shot.videoMediaEntryId&&onOpenMedia(shot.videoMediaEntryId)}>{shot.videoName||"查看视频详情"}</button></div>}
        <div className="shot-actions"><button onClick={()=>void uploadVideo(shot.id)}>{shot.videoMediaEntryId?"替换视频":"上传视频"}</button><button onClick={()=>setVideoPickerShot(shot.id)}>从视频库选择</button>{shot.videoMediaEntryId&&<button onClick={()=>void setVideo(shot.id,null)}>解除视频</button>}<button onClick={() => setEditing(toUnitInput(shot))}>编辑</button><button className="danger" onClick={() => void remove(shot)}>删除</button></div>
      </article>)}{!project.units.some(unit => unit.parentId === scene.id) && <div className="empty-inline">尚未创建镜头</div>}</div>
    </section>)}</div> : <div className="empty-state compact"><Clapperboard size={34} /><strong>这个项目还没有场景</strong><span>静帧项目可以不建场景；动画项目可用“场景 → 镜头”组织制作单元。</span></div>}
    {editing && <UnitEditor value={editing} scenes={scenes} onClose={() => setEditing(null)} onSave={save} />}
    {videoPickerShot&&<ProjectVideoPicker onClose={()=>setVideoPickerShot(null)} onChoose={entryId=>{const shotId=videoPickerShot;setVideoPickerShot(null);void setVideo(shotId,entryId)}}/>}
  </div>;
}

function ProjectTasks({ project, notify, refresh }: { project: CreativeProject; notify: Props["notify"]; refresh: () => Promise<void> }) {
  const [editing, setEditing] = useState<ProjectTaskInput | null>(null); const [dragging, setDragging] = useState<string | null>(null);
  const save = async (input: ProjectTaskInput) => { try { await api.saveProjectTask(input); setEditing(null); await refresh(); } catch (error) { notify(String(error), true); } };
  const drop = async (status: ProjectTaskStatus, index: number) => { if (!dragging) return; try { await api.moveProjectTask(dragging, status, index); await refresh(); } catch (error) { notify(String(error), true); } finally { setDragging(null); } };
  const remove = async (task: ProjectTask) => { if (!window.confirm(`删除任务“${task.title}”？`)) return; try { await api.deleteProjectTask(task.id); await refresh(); } catch (error) { notify(String(error), true); } };
  return <div className="kanban"><div className="project-tools"><button className="primary-button compact" onClick={() => setEditing(emptyTask(project.id))}><Plus size={14} />新建任务</button><span>完成 {project.progress}% · 拖动卡片切换状态</span></div><div className="kanban-columns">{taskColumns.map(column => { const tasks = project.tasks.filter(task => task.status === column.id); return <section key={column.id} className={`kanban-column ${column.id}`} onDragOver={event => event.preventDefault()} onDrop={() => void drop(column.id, tasks.length)}><header><strong>{column.label}</strong><span>{tasks.length}</span></header>{tasks.map((task, index) => <article draggable key={task.id} onDragStart={() => setDragging(task.id)} onDragOver={event => event.preventDefault()} onDrop={event => { event.stopPropagation(); void drop(column.id, index); }}><div className={`task-priority ${task.priority}`}>{priorityLabel(task.priority)}</div><h4>{task.title}</h4>{task.description && <p>{task.description}</p>}<footer><span><CalendarDays size={12} />{task.dueDate || "未设日期"}</span><div><button onClick={() => setEditing(toTaskInput(task))}>编辑</button><button className="danger" onClick={() => void remove(task)}><Trash2 size={13} /></button></div></footer></article>)}<button className="kanban-add" onClick={() => setEditing({ ...emptyTask(project.id), status: column.id })}><Plus size={14} />添加任务</button></section>; })}</div>{editing && <TaskEditor value={editing} units={project.units} assets={project.assets} onClose={() => setEditing(null)} onSave={save} />}</div>;
}

function ProjectBoards({ project, notify, refresh, onOpenReference }: { project: CreativeProject; notify: Props["notify"]; refresh: () => Promise<void>; onOpenReference: (id: string) => void }) {
  const [available, setAvailable] = useState<ReferenceBoardSummary[]>([]); useEffect(() => { void api.listReferenceBoards().then(setAvailable).catch(error => notify(String(error), true)); }, []);
  const create = async () => { const name = window.prompt("新参考板名称", `${project.name} · 主参考` )?.trim(); if (!name) return; try { const board = await api.createReferenceBoard(name); await api.linkProjectBoard(project.id, board.id, !project.mainBoardId); await refresh(); } catch (error) { notify(String(error), true); } };
  const link = async (boardId: string) => { if (!boardId) return; try { await api.linkProjectBoard(project.id, boardId, !project.mainBoardId); await refresh(); } catch (error) { notify(String(error), true); } };
  return <div><div className="project-tools"><button className="primary-button compact" onClick={() => void create()}><Plus size={14} />创建参考板</button><select defaultValue="" onChange={event => { void link(event.target.value); event.currentTarget.value = ""; }}><option value="">链接已有参考板…</option>{available.filter(board => !project.boards.some(link => link.boardId === board.id)).map(board => <option value={board.id} key={board.id}>{board.name}</option>)}</select></div>{project.boards.length ? <div className="project-board-list">{project.boards.map(board => <article key={board.boardId} className={board.isMain ? "main" : ""}><Images size={28} /><div><strong>{board.name}</strong><span>{board.itemCount} 张图片 · {board.isMain ? "主参考板" : "附加参考板"}</span></div><button onClick={() => onOpenReference(board.boardId)}><ExternalLink size={14} />打开</button><button onClick={async () => { try { await api.openReferenceWindow(board.boardId); } catch (error) { notify(String(error), true); } }}><ExternalLink size={14} />悬浮</button>{!board.isMain && <button onClick={async () => { await api.setMainProjectBoard(project.id, board.boardId); await refresh(); }}>设为主板</button>}<button className="danger" onClick={async () => { await api.unlinkProjectBoard(project.id, board.boardId); await refresh(); }}><Unlink size={14} />解除</button></article>)}</div> : <div className="empty-state compact"><Images size={34} /><strong>尚未关联参考板</strong><span>参考板保持独立；解除关联或删除项目都不会删除参考板。</span></div>}</div>;
}

function ProjectPaths({ project, notify, refresh }: { project: CreativeProject; notify: Props["notify"]; refresh: () => Promise<void> }) {
  const add = async (kind: ProjectPathInput["kind"], pathType: "file" | "directory", existing?: CreativeProject["paths"][number]) => { const path = await open({ multiple: false, directory: pathType === "directory", filters: pathType === "file" ? [{ name: "CG 工程文件", extensions: ["uproject","blend","hip","hiplc","hipnc","ma","mb","max","c4d","spp","sbs","sbsar","ztl","psd","psb"] }] : undefined }); if (typeof path !== "string") return; const labels = { root: "项目根目录", project_file: "主工程文件", output: "输出目录", custom: "自定义路径" }; const label = existing?.label || (kind === "custom" ? window.prompt("快捷方式名称", "自定义路径")?.trim() : labels[kind]); if (!label) return; try { await api.saveProjectPath({ id: existing?.id, projectId: project.id, kind, label, path, pathType, sortOrder: existing?.sortOrder }); await refresh(); } catch (error) { notify(String(error), true); } };
  return <div><div className="project-tools"><button onClick={() => void add("root", "directory")}><FolderOpen size={14} />项目根目录</button><button onClick={() => void add("project_file", "file")}><FilePlus2 size={14} />主工程文件</button><button onClick={() => void add("output", "directory")}><FolderOpen size={14} />输出目录</button><button onClick={() => void add("custom", "directory")}><Plus size={14} />自定义目录</button><button onClick={() => void add("custom", "file")}><FilePlus2 size={14} />自定义文件</button></div>{project.paths.length ? <div className="project-path-list">{project.paths.map(path => <article key={path.id} className={path.available ? "" : "missing"}><div><FolderOpen size={21} /><div><strong>{path.label}</strong><span>{path.path}</span>{!path.available && <small>路径已失效，请重新定位</small>}</div></div><button disabled={!path.available} onClick={async () => { try { await api.openProjectPath(path.id); } catch (error) { notify(String(error), true); } }}><ExternalLink size={14} />打开</button><button onClick={() => void add(path.kind, path.pathType, path)}>{path.available ? "更换" : "重新定位"}</button><button className="danger" onClick={async () => { await api.deleteProjectPath(path.id); await refresh(); }}><Trash2 size={14} /></button></article>)}</div> : <div className="empty-state compact"><FolderOpen size={34} /><strong>还没有本地工程入口</strong><span>这里只保存安全路径，外部工程文件不会复制进素材库或备份。</span></div>}</div>;
}

function ProjectEditor({ value, onClose, onSave }: { value: ProjectInput; onClose: () => void; onSave: (value: ProjectInput, coverPath?: string) => void }) {
  const [draft, setDraft] = useState(value);
  const [coverPath,setCoverPath]=useState("");
  const [imageQuery,setImageQuery]=useState("");
  const [images,setImages]=useState<MediaEntry[]>([]);
  const set = <K extends keyof ProjectInput>(key: K, next: ProjectInput[K]) => setDraft(previous => ({ ...previous, [key]: next }));
  useEffect(()=>{let cancelled=false;const timer=window.setTimeout(()=>{void api.searchMediaEntries({kind:"image",query:imageQuery,folderId:null,includeChildFolders:true,tags:[],formats:[],favoriteOnly:false,sort:"updated",offset:0,limit:100}).then(page=>{if(!cancelled)setImages(page.items)}).catch(()=>undefined)},180);return()=>{cancelled=true;window.clearTimeout(timer)}},[imageQuery]);
  const pickCover=async()=>{const path=await open({multiple:false,directory:false,filters:[{name:"项目封面",extensions:["jpg","jpeg","png","webp","gif","bmp","tif","tiff"]}]});if(typeof path!=="string")return;setCoverPath(path);setDraft(previous=>({...previous,coverAssetId:null,coverMediaEntryId:null}))};
  return <div className="modal-backdrop"><section className="project-editor modal-card"><header><div><span className="eyebrow">PROJECT SETTINGS</span><h2>{draft.id ? "编辑项目" : "新建创作项目"}</h2></div><button className="icon-button" onClick={onClose}><X size={18} /></button></header>
    <div className="form-grid"><label className="wide">项目名称<input autoFocus value={draft.name} onChange={event => set("name", event.target.value)} /></label><label>项目类型<select value={draft.projectType} onChange={event => set("projectType", event.target.value as ProjectType)}>{Object.entries(typeLabels).map(([id,label]) => <option value={id} key={id}>{label}</option>)}</select></label><label>状态<select value={draft.status} onChange={event => set("status", event.target.value as ProjectInput["status"])}>{Object.entries(statusLabels).map(([id,label]) => <option value={id} key={id}>{label}</option>)}</select></label><label className="wide">项目说明<textarea value={draft.description} onChange={event => set("description", event.target.value)} /></label><label>目标软件<input value={draft.targetTools.join("；")} onChange={event => set("targetTools", split(event.target.value))} placeholder="Unreal Engine；Blender" /></label><label>版本<input value={draft.versions.join("；")} onChange={event => set("versions", split(event.target.value))} placeholder="5.5；4.3" /></label><label>宽度<input type="number" min="1" value={draft.resolutionWidth ?? ""} onChange={event => set("resolutionWidth", numberOrNull(event.target.value))} /></label><label>高度<input type="number" min="1" value={draft.resolutionHeight ?? ""} onChange={event => set("resolutionHeight", numberOrNull(event.target.value))} /></label><label>帧率<input type="number" min="0.1" step="0.01" value={draft.frameRate ?? ""} onChange={event => set("frameRate", numberOrNull(event.target.value))} /></label></div>
    <section className="project-cover-setting"><h3>项目封面</h3><p>可上传本地图片、选用图片库图片，或在项目素材页将素材封面设为项目封面。</p><div className="project-cover-actions"><button className="secondary-button" onClick={()=>void pickCover()}><Images size={15}/>上传图片</button><button className="secondary-button" onClick={()=>{setCoverPath("");setDraft(previous=>({...previous,coverAssetId:null,coverMediaEntryId:null}))}}>清除封面</button><span>{coverPath.split(/[\\/]/).at(-1)|| (draft.coverMediaEntryId?"已选图片库图片":draft.coverAssetId?"使用素材封面":"未设置")}</span></div><input value={imageQuery} onChange={event=>setImageQuery(event.target.value)} placeholder="搜索图片库图片…" aria-label="搜索项目封面图片"/><div className="project-cover-choices">{images.map(entry=><button key={entry.id} className={draft.coverMediaEntryId===entry.id&&!coverPath?"active":""} onClick={()=>{setCoverPath("");setDraft(previous=>({...previous,coverAssetId:null,coverMediaEntryId:entry.id}))}}>{entry.thumbnailFileId&&<img src={mediaLibraryFileUrl(entry.thumbnailFileId)} alt="" loading="lazy"/>}<span>{entry.name}</span></button>)}</div></section>
    <footer><button className="secondary-button" onClick={onClose}>取消</button><button className="primary-button" disabled={!draft.name.trim()} onClick={() => onSave(draft,coverPath||undefined)}>保存项目</button></footer>
  </section></div>;
}

function UnitEditor({ value, scenes, onClose, onSave }: { value: ProjectUnitInput; scenes: ProjectUnit[]; onClose: () => void; onSave: (value: ProjectUnitInput) => void }) { const [draft,setDraft]=useState(value); const set=(key:keyof ProjectUnitInput,next:any)=>setDraft(previous=>({...previous,[key]:next})); return <div className="modal-backdrop"><section className="modal-card compact-editor"><header><h2>{draft.kind === "scene" ? "场景" : "镜头"}</h2><button className="icon-button" onClick={onClose}><X size={18}/></button></header><div className="form-grid"><label className="wide">名称<input autoFocus value={draft.name} onChange={e=>set("name",e.target.value)}/></label>{draft.kind === "shot" && <label className="wide">所属场景<select value={draft.parentId || ""} onChange={e=>set("parentId",e.target.value)}>{scenes.map(scene=><option value={scene.id} key={scene.id}>{scene.name}</option>)}</select></label>}<label className="wide">说明<textarea value={draft.description} onChange={e=>set("description",e.target.value)}/></label>{draft.kind === "shot" && <><label>起始帧<input type="number" value={draft.startFrame ?? ""} onChange={e=>set("startFrame",numberOrNull(e.target.value))}/></label><label>结束帧<input type="number" value={draft.endFrame ?? ""} onChange={e=>set("endFrame",numberOrNull(e.target.value))}/></label><label>覆盖宽度<input type="number" min="1" value={draft.resolutionWidth ?? ""} onChange={e=>set("resolutionWidth",numberOrNull(e.target.value))}/></label><label>覆盖高度<input type="number" min="1" value={draft.resolutionHeight ?? ""} onChange={e=>set("resolutionHeight",numberOrNull(e.target.value))}/></label><label>覆盖帧率<input type="number" step="0.01" value={draft.frameRate ?? ""} onChange={e=>set("frameRate",numberOrNull(e.target.value))}/></label></>}</div><footer><button onClick={onClose}>取消</button><button className="primary-button" disabled={!draft.name.trim()} onClick={()=>onSave(draft)}>保存</button></footer></section></div>; }

function TaskEditor({ value, units, assets, onClose, onSave }: { value: ProjectTaskInput; units: ProjectUnit[]; assets: ProjectAssetLink[]; onClose: () => void; onSave: (value: ProjectTaskInput) => void }) { const [draft,setDraft]=useState(value); const set=(key:keyof ProjectTaskInput,next:any)=>setDraft(previous=>({...previous,[key]:next})); return <div className="modal-backdrop"><section className="modal-card task-editor"><header><h2>{draft.id ? "编辑任务" : "新建任务"}</h2><button className="icon-button" onClick={onClose}><X size={18}/></button></header><div className="form-grid"><label className="wide">标题<input autoFocus value={draft.title} onChange={e=>set("title",e.target.value)}/></label><label>状态<select value={draft.status} onChange={e=>set("status",e.target.value)}>{taskColumns.map(column=><option value={column.id} key={column.id}>{column.label}</option>)}</select></label><label>优先级<select value={draft.priority} onChange={e=>set("priority",e.target.value)}>{(["low","normal","high","urgent"] as ProjectTaskPriority[]).map(value=><option value={value} key={value}>{priorityLabel(value)}</option>)}</select></label><label>场景 / 镜头<select value={draft.unitId || ""} onChange={e=>set("unitId",e.target.value || null)}><option value="">不关联</option>{units.map(unit=><option key={unit.id} value={unit.id}>{unit.kind === "shot" ? "镜头 · " : "场景 · "}{unit.name}</option>)}</select></label><label>截止日期<input type="date" value={draft.dueDate || ""} onChange={e=>set("dueDate",e.target.value || null)}/></label><label className="wide">说明<textarea value={draft.description} onChange={e=>set("description",e.target.value)}/></label><fieldset className="wide task-asset-checks"><legend>关联项目素材</legend>{assets.filter(asset=>!asset.unavailable).map(asset=><label key={asset.assetId}><input type="checkbox" checked={draft.assetIds.includes(asset.assetId)} onChange={e=>set("assetIds",e.target.checked ? [...draft.assetIds,asset.assetId] : draft.assetIds.filter(id=>id!==asset.assetId))}/>{asset.name}</label>)}</fieldset></div><footer><button onClick={onClose}>取消</button><button className="primary-button" disabled={!draft.title.trim()} onClick={()=>onSave(draft)}>保存任务</button></footer></section></div>; }

function ProjectMenu({ project, onEdit, onArchive, onDelete }: { project: ProjectSummary; onEdit: () => void; onArchive: () => void; onDelete: () => void }) { const [open,setOpen]=useState(false); return <div className="project-menu"><button className="icon-button" onClick={()=>setOpen(value=>!value)}><MoreHorizontal size={17}/></button>{open&&<div onMouseLeave={()=>setOpen(false)}><button onClick={onEdit}><Settings2 size={14}/>编辑</button><button onClick={onArchive}>{project.status === "archived" ? <RotateCcw size={14}/> : <Archive size={14}/>}{project.status === "archived" ? "恢复" : "归档"}</button>{project.status === "archived"&&<button className="danger" onClick={onDelete}><Trash2 size={14}/>永久删除</button>}</div>}</div>; }

function toInput(project: ProjectSummary): ProjectInput { return { id: project.id, name: project.name, description: project.description, projectType: project.projectType, status: project.status, targetTools: project.targetTools, versions: project.versions, resolutionWidth: project.resolutionWidth, resolutionHeight: project.resolutionHeight, frameRate: project.frameRate, coverAssetId: project.coverAssetId, coverMediaEntryId:project.coverMediaEntryId }; }
function toUnitInput(value: ProjectUnit): ProjectUnitInput { return { id:value.id,projectId:value.projectId,parentId:value.parentId,kind:value.kind,name:value.name,description:value.description,startFrame:value.startFrame,endFrame:value.endFrame,resolutionWidth:value.resolutionWidth,resolutionHeight:value.resolutionHeight,frameRate:value.frameRate,sortOrder:value.sortOrder }; }
function emptyTask(projectId:string):ProjectTaskInput{return{projectId,unitId:null,title:"",description:"",status:"todo",priority:"normal",dueDate:null,assetIds:[]};}
function toTaskInput(value:ProjectTask):ProjectTaskInput{return{id:value.id,projectId:value.projectId,unitId:value.unitId,title:value.title,description:value.description,status:value.status,priority:value.priority,dueDate:value.dueDate,sortOrder:value.sortOrder,assetIds:value.assetIds};}
function split(value:string){return value.split(/[；;,]/).map(item=>item.trim()).filter(Boolean);}
function numberOrNull(value:string){const parsed=Number(value);return value.trim()&&Number.isFinite(parsed)?parsed:null;}
function priorityLabel(value:ProjectTaskPriority){return{low:"低",normal:"普通",high:"高",urgent:"紧急"}[value];}
